apiVersion: v1
kind: Service
metadata:
  name: {{ TEST_APPLICATION }}
  labels:
    application: {{ TEST_APPLICATION }}
spec:
  selector:
    application: {{ TEST_APPLICATION }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP