---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fg-manual-test-stackset1
spec:
  replicas: 1
  selector:
    matchLabels:
      application: fg-manual-test-stackset1
  template:
    metadata:
      labels:
        application: fg-manual-test-stackset1
    spec:
      containers:
        - name: fg-manual-test-stackset1
          image: inanimate/echo-server
          env:
            - name: ADD_HEADERS
              value: "{\"DeploymentIdentifier\": \"Stack_1\"}"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            requests:
              cpu: 1
              memory: 100Mi
            limits:
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fg-manual-test-stackset2
spec:
  replicas: 1
  selector:
    matchLabels:
      application: fg-manual-test-stackset2
  template:
    metadata:
      labels:
        application: fg-manual-test-stackset2
    spec:
      containers:
        - name: fg-manual-test-stackset2
          image: inanimate/echo-server
          env:
            - name: ADD_HEADERS
              value: "{\"DeploymentIdentifier\": \"Stack_2\"}"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            requests:
              cpu: 1
              memory: 100Mi
            limits:
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: fg-manual-test-stackset1
spec:
  selector:
    application: fg-manual-test-stackset1
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fg-manual-test-stackset2
spec:
  selector:
    application: fg-manual-test-stackset2
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
