apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric-gateway-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fabric-gateway-k8s-api-access
subjects:
  - kind: ServiceAccount
    name: fabric-gateway-service-account
    namespace: fabric